# Generated by Django 5.0.6 on 2024-06-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FrontendTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="Key"),
                ),
                ("text", models.CharField(max_length=1024, verbose_name="Text")),
                (
                    "text_uz",
                    models.CharField(max_length=1024, null=True, verbose_name="Text"),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=1024, null=True, verbose_name="Text"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=1024, null=True, verbose_name="Text"),
                ),
            ],
            options={
                "verbose_name": "Frontend translation",
                "verbose_name_plural": "Frontend translations",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="File"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("video", "Video"), ("image", "Image")],
                        verbose_name="File Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "db_table": "Media",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Site name"
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                        verbose_name="Site logo",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bot token"
                    ),
                ),
                (
                    "host_url",
                    models.URLField(blank=True, null=True, verbose_name="Host URL"),
                ),
            ],
            options={
                "verbose_name": "Settings",
            },
        ),
        migrations.CreateModel(
            name="VersionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("version", models.CharField(max_length=64, verbose_name="Version")),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="Required"),
                ),
            ],
            options={
                "verbose_name": "Version history",
                "verbose_name_plural": "Version histories",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="common.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("common.region",),
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="common.district",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
