# Generated by Django 4.2 on 2024-08-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Section name"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "first"),
                            ("second", "second"),
                            ("third", "third"),
                            ("four", "four"),
                            ("five", "five"),
                            ("six", "six"),
                            ("seven", "seven"),
                            ("text_question", "text_question"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Section number",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="Total Questions"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="branch",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Branch name"
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Question")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Question order"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section_questions",
                        to="tgbot.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
