# Generated by Django 5.0.8 on 2024-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0002_section_remove_telegramprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="telegramprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
