# Generated by Django 5.0.6 on 2024-07-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_alter_userproduct_verification_status"),
        ("olimpic", "0003_olimpic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpic",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olimpic_universities",
                to="bot.university",
            ),
        ),
    ]
