# Generated by Django 4.2.5 on 2024-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0004_olimpic_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpic",
            name="point",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Olimpic number"
            ),
        ),
        migrations.AddField(
            model_name="userolimpic",
            name="olympic_points",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="User Olympic Points"
            ),
        ),
    ]
