# Generated by Django 4.2.5 on 2024-07-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0005_olimpic_point_userolimpic_olympic_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userolimpic",
            name="certificate",
        ),
    ]
