# Generated by Django 4.2.5 on 2024-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0006_remove_userolimpic_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Middle", "Middle"),
                ],
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Question Level",
            ),
        ),
    ]
