# Generated by Django 5.0.6 on 2024-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="coins",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                null=True,
                verbose_name="User Coins",
            ),
        ),
    ]
