# Generated by Django 5.0.6 on 2024-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_telegramprofile_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="birth_day",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Day"),
        ),
    ]
