# Generated by Django 5.0.6 on 2024-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_alter_telegramprofile_birth_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="coins",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="User Coins"
            ),
        ),
    ]
