# Generated by Django 5.0.6 on 2024-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_product_userproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproduct",
            name="verification_status",
            field=models.CharField(
                blank=True,
                choices=[("Jarayonda", "Jarayonda"), ("Sotib olindi", "Sotib olindi")],
                null=True,
                verbose_name="user_verification_status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Product description"),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
