# Generated by Django 5.0.6 on 2024-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_userproduct_verification_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="verification_status",
            field=models.CharField(
                blank=True,
                choices=[("Jarayonda", "Jarayonda"), ("Sotib olindi", "Sotib olindi")],
                default="Jarayonda",
                null=True,
                verbose_name="user_verification_status",
            ),
        ),
    ]
