# Generated by Django 4.2.5 on 2024-07-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_telegramprofile_olimpiada_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramprofile",
            name="olimpiada_points",
        ),
    ]
