# Generated by Django 4.2.5 on 2024-07-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_remove_telegramprofile_olimpiada_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="user_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Middle", "Middle"),
                ],
                max_length=255,
                null=True,
                verbose_name="User Level",
            ),
        ),
    ]
