# Generated by Django 4.2.5 on 2024-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0010_telegramprofile_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="total_olympic_score",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Total Olympic Score"
            ),
        ),
    ]
