# Generated by Django 4.2.5 on 2024-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0011_telegramprofile_total_olympic_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="average_olympic_score",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Average Olympic Score"
            ),
        ),
    ]
